In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
tax = pd.read_csv('./data/Tax_info.csv')
onlinesales = pd.read_csv('./data/Onlinesales_info.csv')
marketinginfo = pd.read_csv('./data/Marketing_info.csv')
discountinfo = pd.read_csv('./data/Discount_info.csv')
customerinfo = pd.read_csv('./data/Customer_info.csv')

In [5]:
tax.head()

      제품카테고리   GST
0   Nest-USA  0.10
1     Office  0.10
2    Apparel  0.18
3       Bags  0.18
4  Drinkware  0.18

In [7]:
onlinesales.head()

,고객ID,거래ID,거래날짜,제품ID,제품카테고리,수량,평균금액,배송료,쿠폰상태
0,USER_1358,Transaction_0000,2019-01-01,Product_0981,Nest-USA,1,153.71,6.5,Used
1,USER_1358,Transaction_0001,2019-01-01,Product_0981,Nest-USA,1,153.71,6.5,Used
2,USER_1358,Transaction_0002,2019-01-01,Product_0904,Office,1,2.05,6.5,Used
3,USER_1358,Transaction_0003,2019-01-01,Product_0203,Apparel,5,17.53,6.5,Not Used
4,USER_1358,Transaction_0003,2019-01-01,Product_0848,Bags,1,16.50,6.5,Used

In [8]:
marketinginfo.head()

           날짜  오프라인비용    온라인비용
0  2019-01-01    4500  2424.50
1  2019-01-02    4500  3480.36
2  2019-01-03    4500  1576.38
3  2019-01-04    4500  2928.55
4  2019-01-05    4500  4055.30

In [9]:
discountinfo.head()

     월    제품카테고리    쿠폰코드  할인율
0  Jan   Apparel  SALE10   10
1  Feb   Apparel  SALE20   20
2  Mar   Apparel  SALE30   30
3  Jan  Nest-USA  ELEC10   10
4  Feb  Nest-USA  ELEC20   20

In [10]:
customerinfo.head()

        고객ID 성별        고객지역  가입기간
0  USER_1358  남     Chicago    12
1  USER_0190  남  California    43
2  USER_0066  남     Chicago    33
3  USER_0345  여  California    30
4  USER_0683  남  California    49